In [ ]:
import numpy as np
import pandas as pd

In [3]:
train=pd.read_csv(r'C:\Users\sumanth\Downloads\datasetb2d9982\dataset\train.csv')

In [12]:
train.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424000

In [15]:
train['PRODUCT_ID'].value_counts()

1925202    1
169598     1
1517197    1
241223     1
2025223    1
          ..
122424     1
1331222    1
2445341    1
726066     1
1072666    1
Name: PRODUCT_ID, Length: 2249698, dtype: int64

In [6]:
test = pd.read_csv(r'C:\Users\sumanth\Downloads\datasetb2d9982\dataset\test.csv')

In [13]:
test.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,NaN,NaN,6142
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,[QUALITY GUARANTEED: Luxury cozy plush polyest...,<b>DCGARING Throw Blanket</b><br><br> <b>Size ...,1622
2,1871949,I-Match Auto Parts Front License Plate Bracket...,"[Front License Plate Bracket Made Of Plastic,D...",Replacement for The Following Vehicles:2020 LE...,7540
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,[Available as a single item or bulk packed. Se...,Our Excellence in Service Lapel Pins feature a...,12442
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",NaN,NaN,6318

In [11]:
test.PRODUCT_ID.value_counts()

604373     1
1654128    1
614885     1
906729     1
2704668    1
          ..
2855578    1
2217330    1
1497563    1
367984     1
1040810    1
Name: PRODUCT_ID, Length: 734736, dtype: int64

In [23]:
test.TITLE.value_counts()

Unknown Title                                                                                                           46
Greatest Hits                                                                                                           33
3dRose Garden Flag, White                                                                                               27
Casotec Back Cover for Mobile (Plastic_Multicolor)                                                                      22
Best of                                                                                                                 21
                                                                                                                        ..
Columbia Women's Bugaboo Pant (Emerald, Medium)                                                                          1
BROCKHAUSEN Bastelbuch Bd. 2 - Das große Buch zum Ausschneiden: Bilderrahmen: Auf dem Bauernhof: Gans                    1
Histoire Philosophique Et Politique Des Etablissements Et Du Commerce Des Europeens Dans Les Deux Indes, Volume 6...     1
Peter England Men's Cotton Sweatshirt (PJSTJSLFO35396_Green_XL)                                                          1
Amsahr 18C1623 Lexmark X3530 Remanufactured Replacement Ink Cartridges - Includes Three Black Cartridges Ink             1
Name: TITLE, Length: 728835, dtype: int64

In [16]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734736 entries, 0 to 734735
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   PRODUCT_ID       734736 non-null  int64
 1   TITLE            734731 non-null  object
 2   BULLET_POINTS    458814 non-null  object
 3   DESCRIPTION      354735 non-null  object
 4   PRODUCT_TYPE_ID  734736 non-null  int64
dtypes: int64(2), object(3)
memory usage: 28.0+ MB

In [25]:
train[train['TITLE']=='Unknown Title']

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
15911,729215,Unknown Title,NaN,NaN,1,590.550
32390,719168,Unknown Title,NaN,NaN,1,600.000
59224,775701,Unknown Title,NaN,NaN,97,598.424
92185,482542,Unknown Title,NaN,NaN,12786,800.000
97645,720192,Unknown Title,NaN,NaN,6108,583.000
...,...,...,...,...,...,...
2112722,1509891,Unknown Title,NaN,NaN,1,610.235
2119452,714905,Unknown Title,NaN,NaN,1,600.000
2148319,705489,Unknown Title,NaN,NaN,17,775.000
2149997,646920,Unknown Title,NaN,NaN,1,425.196
2158902,720189,Unknown Title,NaN,NaN,224,583.000

In [17]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249698 entries, 0 to 2249697
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   PRODUCT_ID       int64
 1   TITLE            object
 2   BULLET_POINTS    object
 3   DESCRIPTION      object
 4   PRODUCT_TYPE_ID  int64
 5   PRODUCT_LENGTH   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 103.0+ MB

In [19]:
te=test.drop('TITLE',axis=1)

In [21]:
te['TITLE_replace']=test['TITLE']
te.head()

,PRODUCT_ID,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,TITLE_replace
0,604373,NaN,NaN,6142,Manuel d'Héliogravure Et de Photogravure En Re...
1,1729783,[QUALITY GUARANTEED: Luxury cozy plush polyest...,<b>DCGARING Throw Blanket</b><br><br> <b>Size ...,1622,DCGARING Microfiber Throw Blanket Warm Fuzzy P...
2,1871949,"[Front License Plate Bracket Made Of Plastic,D...",Replacement for The Following Vehicles:2020 LE...,7540,I-Match Auto Parts Front License Plate Bracket...
3,1107571,[Available as a single item or bulk packed. Se...,Our Excellence in Service Lapel Pins feature a...,12442,PinMart Gold Plated Excellence in Service 1 Ye...
4,624253,NaN,NaN,6318,"Visual Mathematics, Illustrated by the TI-92 a..."

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
te.head()

,PRODUCT_ID,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,TITLE_replace,index
0,604373,NaN,NaN,6142,Manuel d'Héliogravure Et de Photogravure En Re...,0
1,1729783,[QUALITY GUARANTEED: Luxury cozy plush polyest...,<b>DCGARING Throw Blanket</b><br><br> <b>Size ...,1622,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,0
2,1871949,"[Front License Plate Bracket Made Of Plastic,D...",Replacement for The Following Vehicles:2020 LE...,7540,I-Match Auto Parts Front License Plate Bracket...,0
3,1107571,[Available as a single item or bulk packed. Se...,Our Excellence in Service Lapel Pins feature a...,12442,PinMart Gold Plated Excellence in Service 1 Ye...,0
4,624253,NaN,NaN,6318,"Visual Mathematics, Illustrated by the TI-92 a...",0